#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 6206-webs
    bind *:80
    mode http
    balance roundrobin
    server 6133-web-01 54.82.230.220:80 check
    server 6133-web-02 18.208.245.207:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart